camera:
  source: 0
  width: 1080
  height: 1080
  fps: 30

model:
  path: src\yolo11l.pt
  confidence_threshold: 0.6
  iou_threshold: 0.45

output:
  save_dir: outputs
  save_interval: 30  # frames

training:
  epochs: 100
  batch_size: 8
  img_size: 640
  data: "data/data.yaml"

testing:
  data: "data/data.yaml"

inference:
  path: "runs/detect/yolov11-glasses_20250410_154720/weights/best.pt"
  test_data: "data/test/images"
augmentation:
  hsv_h: 0.015
  hsv_s: 0.7
  hsv_v: 0.4
  flipud: 0.5


logging:
  level: "INFO"
  file: "logs/glasses_detection.log"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"